cora:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 0.005
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.5
  tau_g: 0.5
  tau_m: 1.0
  tau_t: 0.5
  tau_tn: 1.0
  tau_sub: 0.5
  tau_subn: 0.5
  lambda_n: 0.0002
  lambda_g: 0.0035
  lambda_sub: 0.0002
  w_g: 4
  w_m: 1
  w_t: 1
  w_tn: 1 
  w_sub: 1
  w_subn: 0.1
  epochs: 150
  batch_size_1: null 
  batch_size_2: null 
  random_drop: false
  sample_method: s_walk
  sub_rate: 0.1
  s_walk: 3
  aggregation: node 
  n_walk: 10

citeseer:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 0.005
  drop_feature_rate: 0.4
  drop_incidence_rate: 0.4
  tau_n: 0.5
  tau_g: 0.5
  tau_m: 1.0
  tau_t: 0.5
  tau_tn: 1.0
  tau_sub: 0.5
  tau_subn: 0.5
  lambda_n: 0.0002
  lambda_g: 0.0035
  lambda_sub: 0.0002
  w_g: 4
  w_m: 1
  w_t: 1
  w_tn: 1 
  w_sub: 1
  w_subn: 0.1
  epochs: 150
  batch_size_1: null 
  batch_size_2: null 
  random_drop: false
  sample_method: s_walk
  sub_rate: 0.1
  s_walk: 3
  aggregation: node 
  n_walk: 10
